name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # For cosign

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to GHCR and Docker Hub
        uses: docker/build-push-action@v5 
        id: build-and-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/obeone/auto_docker_proxy:latest
            docker.io/obeoneorg/auto_docker_proxy:latest
          platforms: linux/amd64,linux/arm64,linux/i386

      - name: Set up cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign the container image with cosign
        run: |
          cosign sign --yes ghcr.io/obeone/auto_docker_proxy@${DIGEST}
          cosign sign --yes docker.io/obeoneorg/auto_docker_proxy@${DIGEST}
        env:
          COSIGN_EXPERIMENTAL: true
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
